GET http://localhost:8080/persons

###

GET http://localhost:8080/persons/1

###

POST http://localhost:8080/persons
Content-Type: application/json

{
  "name": "Sebastian",
  "email": "basti@gmail.com",
  "birthdate": "2002-09-01"
}
